### ISSUE TITLE
Write smoke test that port defaults to 8080 and `main()` works

### ISSUE THREAD

**Issue by casey** [soenkehahn/foo#27]
This adds a test named `bar` that isn't run by default:

```toml
[[test]]
name = "bar"
path = "bar.rs"
test = false
```
